// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZPGNXKVTSKUjUl_9_ltoKJlTxeublac',
    appId: '1:116530889383:web:fac30c66c3c3d13bc15182',
    messagingSenderId: '116530889383',
    projectId: 'vnu-student',
    authDomain: 'vnu-student.firebaseapp.com',
    storageBucket: 'vnu-student.firebasestorage.app',
    measurementId: 'G-PSSG5368V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqjqFzt6p3n96_tBmWjgYaYJuZvy9QhOE',
    appId: '1:116530889383:android:aa7b4fd752465798c15182',
    messagingSenderId: '116530889383',
    projectId: 'vnu-student',
    storageBucket: 'vnu-student.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFGG3uki8ND7xIJ4SwF6Ac3UahTJcUX-A',
    appId: '1:116530889383:ios:a191e650641c345bc15182',
    messagingSenderId: '116530889383',
    projectId: 'vnu-student',
    storageBucket: 'vnu-student.firebasestorage.app',
    iosBundleId: 'com.example.vnuStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFGG3uki8ND7xIJ4SwF6Ac3UahTJcUX-A',
    appId: '1:116530889383:ios:a191e650641c345bc15182',
    messagingSenderId: '116530889383',
    projectId: 'vnu-student',
    storageBucket: 'vnu-student.firebasestorage.app',
    iosBundleId: 'com.example.vnuStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFZPGNXKVTSKUjUl_9_ltoKJlTxeublac',
    appId: '1:116530889383:web:28b156f693507fc4c15182',
    messagingSenderId: '116530889383',
    projectId: 'vnu-student',
    authDomain: 'vnu-student.firebaseapp.com',
    storageBucket: 'vnu-student.firebasestorage.app',
    measurementId: 'G-8W5M4HQ60Q',
  );
}
